---
# Configuration file, to deploy the BootCamp2020 projects on Surge

name: "Deployment of bootcamp projects on Surge.sh."
on:
 push:
  branches:
   - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12

    - name: Install Surge
      run: npm install -g surge

    - name: Deploy to Surge
      run:  surge ./ bcamp20_proj_001.surge.sh/ --token ${{secrets.PROJECTS_SECRET}}